import type { NarrativeBeat } from "./NarrativeRoute";

// Editorial paraphrases, never fabricated quotations. Provenance lives in the
// companion source ledger; no private source documents are shipped to visitors.
export const personBeats: NarrativeBeat[] = [
  { id: "person-b01", band: [0,.12], label: "01 · Open clearing / identity", heading: "The person underneath the roles.", reveal: "diagonal-mask", paragraphs: ["Student, builder, MUN organiser, future engineer. Those names describe parts of my life; none is a complete account of the person living it.", "The current picture is someone trying to become capable and useful, while keeping room for freedom, people, curiosity and experience."] },
  { id: "person-b02", band: [.12,.27], label: "Ambition / a working direction", heading: "What would make the ambition worth it?", reveal: "tracking-settle", paragraphs: ["I want to be trusted with difficult problems. I also want to become someone I would admire for the way I handled them.", "That ideal is deliberately unfinished. Capability, character, relationships and contribution belong in it; their final order is still an open question."] },
  { id: "person-b03", band: [.27,.4], label: "Desire / selection", heading: "A possibility is not yet a reason.", reveal: "film-mask", paragraphs: ["Desire gives me a direction: a timetable that distributes work fairly, a room where younger students can practise debate, a portfolio that represents a real person.", "But imagining something does not mean it deserves to exist. The refinement that matters to me is choosing which good possibilities are worth making real."] },
  { id: "person-b04", band: [.4,.53], label: "Freedom / the complication", heading: "Room to choose. Something to choose for.", reveal: "line-unfold", paragraphs: ["Money matters when it removes forced decisions. Time matters when I can decide what receives it. Work, place, relationships, thought and experience each bring another kind of freedom.", "Keeping every option open also has a cost. Depth in a craft or a relationship asks for commitment. I have not settled the balance between agency and the choices that make a life specific."] },
  { id: "person-b05", band: [.53,.66], label: "Capability / current self-assessment", heading: "The label has to catch up with the work.", reveal: "tracking-settle", paragraphs: ["I have used HTML and CSS independently and built real software with substantial AI assistance. Understanding generated code, directing a product and independently engineering a difficult system are different abilities.", "My independent programming depth is earlier than my ambition toward AI and machine learning. I sometimes reduce assistance deliberately so that practice develops the capability, rather than only producing the output."] },
  { id: "person-b06", band: [.66,.78], label: "Experience / meaningful risk", heading: "A life cannot be only an optimisation.", reveal: "quiet-emergence", paragraphs: ["Travel, attempts that might fail, relationships and unfamiliar situations matter alongside achievement. Safety alone would leave too much of life unexperienced.", "That is a preference about how I want to live, not proof that every risk is worthwhile. The question is what the risk makes possible, and whether the possibility deserves it."] },
  { id: "person-b07", band: [.78,.9], label: "People / a model that can change", heading: "Other people change the picture.", reveal: "offset-alignment", paragraphs: ["Trusted friends have challenged how I see myself. One direct conversation after MUN made me acknowledge a tendency to be overly formal and to please people.", "Trust, reciprocity and the willingness to be vulnerable give relationships depth. They also complicate an ideal of complete independence. That tension belongs in the picture."] },
  { id: "person-b08", band: [.9,1], label: "One person / several lenses", heading: "Still becoming. Still answerable to evidence.", reveal: "quiet-emergence", paragraphs: ["Growth is the connection between these ideas. Building gives them consequences; leadership brings other people into them; experience can force them to change.", "AURA’s current account is mostly drawn from my own conversations. It is a working model, with room for other perspectives and for correction."], exits: [{href:"/stay/builder/",label:"The Builder",place:"Thought becomes a system"},{href:"/stay/thinker/",label:"The Thinker",place:"The values beneath it"}] },
];

export const builderBeats: NarrativeBeat[] = [
  { id: "builder-b01", band: [0,.1], label: "02 · Timber frame / method", heading: "The Builder", reveal: "line-unfold", paragraphs: ["A recurring move in my work is to turn an abstract want into explicit rules, then find the cases those rules cannot yet handle.", "The planner, MUN teaching and AURA share that shape. Here is what it looks like when a useful idea becomes a system."] },
  { id: "builder-b02", band: [.1,.2], label: "Study Planner / the problem", heading: "A calendar was only the surface.", reveal: "tracking-settle", paragraphs: ["An IB workload has competing subjects, different priorities and a limited week. The Study Planner began in HTML, CSS and JavaScript, then grew into a scheduling problem.", "HL, SL and extracurricular priorities needed different weights. Decimal values allowed finer control; session blocks and break days constrained what a generated plan could reasonably contain."] },
  { id: "builder-b03", band: [.2,.32], label: "Study Planner / conflicting rules", heading: "Priority is not permission to take over.", reveal: "diagonal-mask", paragraphs: ["Some subjects appeared too often because priority scaling interacted with generation logic. A high weight was turning into an unfair distribution.", "I investigated the rules rather than treating each bad timetable as a separate mistake. Limits on repetition, session length and breaks had to work alongside the weighting."] },
  { id: "builder-b04", band: [.32,.44], label: "Study Planner / state and iteration", heading: "Then the timetable had to be lived.", reveal: "film-mask", paragraphs: ["Local storage kept the plan. Day and week views changed with the planning horizon. Focus Mode added tasks, completion tracking, timers and session start and end popups.", "Each addition made transitions matter: starting work, taking a break, finishing a task, returning later. The difficult part moved from drawing the interface to making those states agree."] },
  { id: "builder-b05", band: [.44,.56], label: "Past papers / two different problems", heading: "A mark. A pattern. A boundary.", reveal: "line-unfold", paragraphs: ["The IGCSE logger records completed papers and scores, then turns that history into graphs, trends and estimates. An estimated direction is not a verified future result.", "A separate topic-compilation idea asks a different question: if part (a) matches a topic and part (b) does not, should the whole question be included? The intended boundary is meaningful question identity, not a coincidental text match.", "That compilation concept is recorded in AURA; I do not present it as a demonstrated feature of the score logger."] },
  { id: "builder-b06", band: [.56,.68], label: "Across projects / a recurring pattern", heading: "Rules are also built for people.", reveal: "offset-alignment", paragraphs: ["A MUN lesson has attention, confidence and procedural knowledge to account for. An event registration flow has payment, verification and pricing states. AURA has evidence, claims and uncertainty.", "Different materials, a similar question: what must be true for this system to behave sensibly when the easy case ends?"], exits: [{href:"/stay/work/#study-planner",label:"Study Planner",place:"Inside the scheduling problem"},{href:"/stay/work/#past-paper-logger",label:"Past Paper Logger",place:"The evidence behind the marks"}] },
  { id: "builder-b07", band: [.68,.82], label: "Iteration / observed project pattern", heading: "Make it real. Inspect what is weak.", reveal: "tracking-settle", paragraphs: ["Attempt something meaningful, ship enough to test it, inspect the weakness, identify a skill gap, learn, and improve. That pattern appears across my project work.", "It has an exit condition: reconsider whether the objective still deserves the effort. Changing a method and abandoning an objective are different decisions; neither should be automatic."] },
  { id: "builder-b08", band: [.82,1], label: "Technical honesty / the next development", heading: "I have built real things. I am not yet the engineer I intend to become.", reveal: "quiet-emergence", paragraphs: ["These projects demonstrate product thinking and AI-assisted building. They do not establish independent mastery of advanced software engineering.", "The next task is to strengthen the ability to design, debug and extend difficult systems myself. The ambition stays; the present claim stays proportionate."], exits: [{href:"/stay/work/",label:"The Work",place:"Five case studies"},{href:"/stay/thinker/",label:"The Thinker",place:"When is improvement enough?"}] },
];

export const thinkerBeats: NarrativeBeat[] = [
  {id:"thinker-b01",band:[0,.12],label:"03 · Quiet water / philosophical model",heading:"The Thinker",reveal:"tracking-settle",paragraphs:["These are ideas I am testing against how I live. Some are endorsed principles; others are interpretations that can still change.","The questions connect ambition to agency, failure to learning, and safety to the cost of a life without depth."]},
  {id:"thinker-b02",band:[.12,.28],label:"Desire / a personal interpretation",heading:"Imagine it. Then ask whether it should exist.",reveal:"film-mask",paragraphs:["I think about human distinctiveness through desire, ingenuity, curiosity and perseverance: the ability to imagine something absent and work to make it real. That is a philosophical interpretation, not a scientific theory.","The filter matters as much as the engine. The good possibilities deserve pursuit; the existence of a desire does not settle whether to act on it."]},
  {id:"thinker-money",band:[.28,.36],label:"Freedom / financial, time, career",heading:"Money buys room. Time gives it somewhere to go.",reveal:"line-unfold",paragraphs:["Financial freedom reduces choices forced by money. Time freedom gives control over where attention goes. Career freedom makes meaningful work a possible choice.","Money stops serving its purpose when acquiring it consumes the agency it was supposed to create."]},
  {id:"thinker-choice",band:[.36,.44],label:"Freedom / people, place, thought, experience",heading:"Choice has more than one dimension.",reveal:"quiet-emergence",paragraphs:["Relationship freedom means choosing connections rather than being trapped by dependence. Geographic freedom makes movement possible; intellectual freedom leaves room to question; experiential freedom leaves room to try.","But maximum optionality can prevent depth. A craft, a person or a responsibility asks us to choose for long enough that other options close. My final definition of freedom remains open."]},
  {id:"thinker-b04",band:[.44,.6],label:"Failure / adaptation",heading:"The failure is evidence. The response decides its value.",reveal:"diagonal-mask",paragraphs:["A failed attempt is an outcome, not a verdict on worth. It becomes useful when it reveals a mistaken method, assumption or objective.","Name what failed. Separate the outcome from identity. Change the smallest thing that matters and attempt again. Repeated contradiction of the objective itself can also be a reason to stop."]},
  {id:"thinker-b05",band:[.6,.76],label:"The Fortress Test / a recorded choice",heading:"Safety has a price of its own.",reveal:"line-unfold",paragraphs:["When asked to choose between complete emotional invulnerability and deep vulnerability, I chose vulnerability. Complete protection would also remove much of the risk and depth that make relationships meaningful.","This was a reasoned choice in a conversation. It does not prove how I would respond to every real loss; it does show that total safety is not the life I want to optimise for."]},
  {id:"thinker-b06",band:[.76,.9],label:"Excellence / a corrected interpretation",heading:"Quality is a relationship across versions.",reveal:"tracking-settle",paragraphs:["I can ship an imperfect first attempt when circumstances call for it and return to improve it. The earlier description of me as a perfectionist missed that distinction.","There is a shadow: improvement can continue without an end. What counts as enough excellence, ambition or money remains an unresolved question, not an inspirational answer I have already found."]},
  {id:"thinker-b07",band:[.9,1],label:"A question carried onward",heading:"What would change my mind?",reveal:"quiet-emergence",paragraphs:["A useful principle has to survive contact with choices, costs and other people. An elegant explanation is not enough evidence on its own.","The stories show where a conversation changed the model. The work shows where a rule encountered the world."],exits:[{href:"/stay/leader/",label:"The Leader",place:"Principles become responsibility"},{href:"/stay/stories/",label:"Stories",place:"Moments that changed the picture"}]},
];
