import type { NarrativeBeat } from "./NarrativeRoute";
export const leaderBeats: NarrativeBeat[] = [
  {id:"leader-b01",band:[0,.14],label:"04 · Courtyard / responsibility",heading:"The Leader",reveal:"film-mask",paragraphs:["My strongest leadership evidence comes from a weekly MUN programme for younger students, and from stepping into work when a formal role was absent.","The useful question is what I actually made possible for other people, and how much of it depended on me being there."]},
  {id:"leader-b02",band:[.14,.36],label:"MUN Club / a weekly teaching system",heading:"A room learns by doing.",reveal:"diagonal-mask",paragraphs:["Weekly one-hour sessions needed more than an explanation of Model United Nations. I designed lessons, icebreakers, short and team debates, role-play scenarios and simulations, using Google Classroom as the online environment.","Younger students could practise the activity itself: form an argument, speak, respond to another delegate, and find a way through the rules. Teaching and session operation were part of the same responsibility."]},
  {id:"leader-b03",band:[.36,.53],label:"Curriculum / procedure becomes usable",heading:"The rules needed a situation.",reveal:"offset-alignment",paragraphs:["Roll call, agenda-setting, motions, moderated and unmoderated caucuses, GSL speeches and points of order became material for exercises and full simulations.","Scenario-based MUN chaos exercises gave students a reason to recall the procedure. Interactive revision and adapting lessons kept the programme connected to how the room was actually learning."]},
  {id:"leader-b04",band:[.53,.68],label:"House activity / an observed example",heading:"An absent co-leader. A job still needing to happen.",reveal:"line-unfold",paragraphs:["At a school House activity, a co-leader was absent. I stepped in to help organise the activity and manage the crowd without holding that formal leadership role.","Alongside the ongoing club work, it suggests a pattern of responding to an organisational gap. It is evidence of taking responsibility, not evidence that every intervention I make is the right one."]},
  {id:"leader-b05",band:[.68,.84],label:"Communication / another practical setting",heading:"Structure makes participation possible.",reveal:"tracking-settle",paragraphs:["STRAT MUN was a separate conference effort: planning, committee topics, difficulty calibration, country allocation, advertising and branding. It sits alongside the weekly club, rather than replacing it.","Both settings required ideas to become understandable to someone else. A procedure has little value if the people using it cannot act on it."]},
  {id:"leader-b06",band:[.84,1],label:"The counterpoint / unresolved leadership risk",heading:"Who can act when I step away?",reveal:"quiet-emergence",paragraphs:["Taking over when others contribute less can keep a programme running, while also creating dependence on one person. Over-ownership is a recognised risk in my current model.","No major leadership failure has been documented in AURA’s evidence so far. That is a gap in the record, not a clean record. Delegation, feedback and systems that survive my absence are development questions, not outcomes I claim to have achieved."],exits:[{href:"/stay/stories/",label:"Stories",place:"The events behind the ideas"},{href:"/stay/work/#mun-club",label:"MUN Club",place:"The teaching system"}]},
];

export const storyBeats: NarrativeBeat[] = [
  {id:"stories-b01",band:[0,.12],label:"05 · Lantern path / evidence at its actual size",heading:"What changed the picture?",reveal:"film-mask",paragraphs:["A few moments explain more than a list of qualities can. What happened, what it changed, and what still cannot be concluded from it.","These are selected public stories, not a complete biography."]},
  {id:"stories-b02",band:[.12,.3],label:"A small reputation / observation",heading:"The Adharsh mentality",reveal:"tracking-settle",paragraphs:["Some people who know me have used that phrase as shorthand for confidence. Some reportedly imagine how I might act when they want to be more confident themselves.","I think the description can be exaggerated or partly a joke. The evidence supports a small social reputation among some peers; it cannot establish broad influence on everyone around me.","That limitation matters. A flattering story should still be told at the size its evidence supports."]},
  {id:"stories-b03",band:[.3,.48],label:"After MUN / a friend’s intervention",heading:"An answer I had been avoiding.",reveal:"offset-alignment",paragraphs:["After an MUN conference, a trusted friend challenged my formality and tendency to please people, and encouraged me to be more open.","The idea was not new to me. Accepting it openly was. I recognised a tendency to be docile and too easy to walk over, and began trying to change it.","One honest conversation changed my self-understanding. Whether the behaviour has changed consistently is still a question, rather than a finished transformation."]},
  {id:"stories-fortress",band:[.48,.59],label:"The Fortress Test / a recorded choice",heading:"The door could stay locked forever.",reveal:"quiet-emergence",paragraphs:["The question offered complete emotional invulnerability or deep vulnerability. I chose vulnerability because protection would also remove the possibility of depth.","It helped explain why wanting independence can coexist with wanting trust and connection. A conversational choice gives the model a direction; real experience still has to test it."]},
  {id:"stories-persistence",band:[.59,.7],label:"AURA / an observable project history",heading:"Keep the objective. Replace the method.",reveal:"line-unfold",paragraphs:["A portfolio-first attempt became discovery through conversation, then a structured person model. Two Genesis drafts, a Personal Operating System and an evidence supplement were eventually brought together.","The methods changed while the objective of accurate understanding survived. The project itself is evidence of that effort; it is not proof that I should persist with every objective indefinitely."]},
  {id:"stories-b05",band:[.7,.9],label:"Technical competence / explicit correction",heading:"The more accurate account was less flattering.",reveal:"tracking-settle",paragraphs:["An earlier interpretation made my programming depth sound more advanced than I believed it was. I corrected it: my recent building uses substantial AI assistance, and I do not regard that as independent engineering mastery.","The correction kept the ambition and changed the present claim. Reducing assistance at times creates room to practise the capability the future identity requires.","The remaining question is what learning conditions will sustain depth after novelty disappears. Naming the gap does not mean it has already been closed."]},
  {id:"stories-b06",band:[.9,1],label:"Different moments / one revisable model",heading:"A story can change the next decision.",reveal:"quiet-emergence",paragraphs:["These moments complicate the same person: confidence with uncertainty, persistence with revision, ambition with an honest account of current ability.","The work gives those patterns another kind of evidence. The future asks what to do with the distance they reveal."],exits:[{href:"/stay/work/",label:"The Work",place:"Five systems and their limits"},{href:"/stay/future/",label:"The Future",place:"A direction still being built"}]},
];

export const workBeats: NarrativeBeat[] = [
  {id:"work-b01",band:[0,.09],label:"06 · Workshop / five case studies",heading:"The things I actually built.",reveal:"film-mask",paragraphs:["Each station begins with a problem, follows the rules and difficulty, and ends with what the work can honestly demonstrate.","Study Planner. IGCSE Past Paper Logger & Analytics. MUN Club. SNRLED Parties. Project AURA. The evidence differs, so the accounts have different lengths."]},
  {id:"study-planner",band:[.09,.14],label:"01 / Study Planner / why",heading:"A week has to make room for competing work.",reveal:"line-unfold",paragraphs:["The planner began as an HTML, CSS and JavaScript application for organising an IB workload. Making a schedule was easy to describe; distributing time sensibly was harder.","Higher Level and Standard Level subjects, extracurricular work and adjustable priorities all competed for a finite set of sessions. The scheduling engine became the centre of the project."]},
  {id:"planner-rules",band:[.14,.2],label:"Study Planner / how and difficulty",heading:"Weights, limits and breaks have to agree.",reveal:"tracking-settle",paragraphs:["Decimal weighting allowed finer subject priorities. Sessions commonly used 90-minute blocks, with rules to prevent excessive repetition of a subject inside a session. Breaks and break days were part of the constraints.","A distribution problem appeared: priority scaling caused some subjects to recur too often. I investigated the generation rules and refined them instead of manually correcting each timetable."]},
  {id:"planner-iteration",band:[.2,.25],label:"Study Planner / iteration and present evidence",heading:"A plan becomes a sequence of states.",reveal:"quiet-emergence",paragraphs:["Local storage, day and week views, tasks, popups and timers extended the original application. Focus Mode added fullscreen daily work, completion tracking and a Pomodoro-like sequence.","The resulting work demonstrates a rule-governed scheduling problem and attention to state transitions. It does not establish an independently verified improvement in grades or productivity."]},
  {id:"past-paper-logger",band:[.25,.33],label:"02 / IGCSE logger / why and what",heading:"What did the history of practice reveal?",reveal:"film-mask",paragraphs:["A single mark tells me how one paper went. A record of completed IGCSE papers and scores can show how practice is changing over time.","The logger turns those records into performance graphs, trend analysis and future-performance estimates. The purpose is to make practice history useful when deciding what to work on next."]},
  {id:"logger-boundaries",band:[.33,.41],label:"Logger / interpretation and limits",heading:"An estimate must stay an estimate.",reveal:"tracking-settle",paragraphs:["Recorded points and a projected direction answer different questions. The project’s prediction accuracy has not been established; an illustrative graph here is not a set of actual scores.","A separate topic-compilation concept in AURA concerns local IB papers and semantic question boundaries. Matching part (a) should not automatically include an unrelated part (b). That design idea is distinct from this score logger, and is not presented as an implemented analytics feature."]},
  {id:"mun-club",band:[.41,.49],label:"03 / MUN Club / why and structure",heading:"Build the conditions for a room to participate.",reveal:"offset-alignment",paragraphs:["The weekly club gave younger students a place to practise MUN. I designed and ran one-hour sessions, with Google Classroom supporting the online organisation.","Icebreakers, short debates, team debates, role-play and full simulations made the programme experiential. Its materials had to account for confidence, attention and different familiarity with procedure."]},
  {id:"mun-practice",band:[.49,.57],label:"MUN Club / operation and reflection",heading:"A lesson. A debate. A simulation. Then another week.",reveal:"line-unfold",paragraphs:["Rules of Procedure, roll call, agenda-setting, motions, caucuses, speeches and points of order became exercises rather than only descriptions. Interactive revision gave students repeated ways to use them.","The project shows curriculum design, teaching and operational ownership. It also exposes the leadership question of whether a programme can work without one person repeatedly absorbing the responsibility. No measured student outcome is claimed here."]},
  {id:"snrled",band:[.57,.66],label:"04 / SNRLED Parties / archived project",heading:"Registration was a flow, not a single form.",reveal:"diagonal-mask",paragraphs:["SNRLED combined an event frontend with registration and administrative workflows. The preserved repository contains a multi-step registration wizard, pricing logic, payment-proof uploads and manual verification.","Supabase schema and storage support registrations, payment proofs and event settings. The distinction between pending, verified and rejected states matters across both visitor and admin views."]},
  {id:"snrled-states",band:[.66,.75],label:"SNRLED / difficulty and historical status",heading:"One state change reaches several parts of the product.",reveal:"tracking-settle",paragraphs:["Pricing phases depend on event settings and registration counts; administrative verification changes payment and registration state. Frontend, API logic and database structure have to describe the same flow.","This portfolio presents SNRLED as archived, with deployment inactive and Supabase disconnected, as recorded in the supplied project handoff. The source supports the system description; live payments, exact thresholds and current service operation are not demonstrated here."]},
  {id:"project-aura",band:[.75,.83],label:"05 / Project AURA / the first problem",heading:"The portfolio kept asking a harder question.",reveal:"film-mask",paragraphs:["An ambitious portfolio needed choices about identity, stories and principles. Improving the design did not answer what person it should represent.","The bottleneck moved from presentation to understanding. I paused the portfolio-first approach and began a longer process of questioning, evidence and revision."]},
  {id:"aura-preview",band:[.83,.92],label:"AURA / structure and current status",heading:"The interface became a consequence.",reveal:"quiet-emergence",paragraphs:["Genesis records why the project exists. A person model keeps current conclusions and their evidence. The public portfolio communicates selected parts of that model.","AURA is an ongoing personal inquiry with AI collaboration, not published academic research or a completed psychological theory. Its strongest result is a more traceable and revisable account, including what it does not yet know."],exits:[{href:"/stay/aura/",label:"Enter AURA",place:"Why all these paths belong together"}]},
  {id:"work-b07",band:[.92,1],label:"The work / what carries forward",heading:"The pattern is visible. The limits are too.",reveal:"quiet-emergence",paragraphs:["These systems show what I have attempted and where the difficult work appeared: scheduling fairness, evidence interpretation, teaching, product state and accurate representation.","AI-assisted software building, independent technical development and demonstrated leadership are related parts of the same story. They carry different kinds of evidence."],exits:[{href:"/stay/future/",label:"The Future",place:"The next capability to build"},{href:"/stay/aura/",label:"Project AURA",place:"The underlying question"}]},
];

export const futureBeats: NarrativeBeat[] = [
  {id:"future-b01",band:[0,.16],label:"07 · Open horizon / direction",heading:"The Future",reveal:"line-unfold",paragraphs:["The direction is advanced AI and machine learning, intelligent systems, difficult software and research where the question is still open.","That describes what I want to become capable of doing. It does not describe a profession or level of mastery I already hold."]},
  {id:"future-b02",band:[.16,.36],label:"Present / the constraint",heading:"Start with the person who is here.",reveal:"tracking-settle",paragraphs:["I am pursuing the IB Diploma while building projects, experimenting and taking responsibility in MUN. School is a major current constraint on time and attention.","My technical exploration has been broad. Sustaining depth once the novelty fades has been harder, and the reasons are not yet fully understood."]},
  {id:"future-b03",band:[.36,.58],label:"Development / a real distance",heading:"Understanding the output is not the end of learning.",reveal:"diagonal-mask",paragraphs:["I want to independently design, debug, optimise and extend systems, with mathematical and technical depth strong enough for the work I am aiming toward.","Sometimes I reduce AI assistance to practise; elsewhere I use it to accelerate product development. The desired relationship is assistance that increases leverage while capability continues to grow."]},
  {id:"future-b04",band:[.58,.8],label:"Open question / research and building",heading:"Which difficult questions deserve years?",reveal:"quiet-emergence",paragraphs:["Neural networks, transformers, intelligent software and human-computer collaboration belong to the direction I want to explore. The exact career endpoint is not locked.","The balance between research depth and product building remains open. So does what enough ambition means when capability, freedom, relationships and experience all need room."]},
  {id:"future-b05",band:[.8,1],label:"Direction / still subject to evidence",heading:"A direction, not an arrival.",reveal:"film-mask",paragraphs:["The aim is to build the capability rather than prematurely claim the identity. A consequential project or decision may change the route.","AURA is the place where the current picture can be examined and revised. It is also why the paths you have just travelled belong to the same experience."],exits:[{href:"/stay/aura/",label:"Project AURA",place:"The question underneath the garden"}]},
];

export const auraBeats: NarrativeBeat[] = [
  {id:"aura-b01",band:[0,.12],label:"08 · Archive / the realisation",heading:"The garden was an expression all along.",reveal:"quiet-emergence",paragraphs:["Person, Builder, Thinker, Leader, Stories, Work and Future are different views of one evolving account.","AURA is the question that made that account necessary."]},
  {id:"aura-b02",band:[.12,.24],label:"Genesis / presentation reached its limit",heading:"It started as a portfolio.",reveal:"film-mask",paragraphs:["Every design decision needed an answer about the person it was supposed to represent. Which stories mattered? What principles held? What should someone understand after leaving?", "I could keep perfecting the presentation, but the answers underneath it were still assumptions."]},
  {id:"aura-realisation",band:[.24,.38],label:"The shift / identity before expression",heading:"So I changed the question.",reveal:"diagonal-mask",paragraphs:["Instead of asking how to build the perfect portfolio, I began asking how to understand the person it should represent.","The portfolio was not abandoned. Its role changed: it would communicate selected understanding, rather than manufacture an identity to communicate."]},
  {id:"aura-discovery",band:[.38,.49],label:"01 / Discovery / the structure opens",heading:"The first answer was rarely the whole answer.",reveal:"tracking-settle",paragraphs:["Conversation led to more questions. Definitions changed; assumptions were challenged. The work became discovery before documentation.","A document can record an understanding reached through that process. Writing one cannot substitute for having done the questioning."]},
  {id:"aura-evidence",band:[.49,.62],label:"02 / Evidence / an archive takes shape",heading:"Attach the claim to something that happened.",reveal:"film-mask",paragraphs:["Projects, stories, repeated behaviour and decisions gave claims something to answer to. The planner’s fairness problem and the MUN programme carry more information than an adjective about me.","Most of AURA’s evidence is still self-reported through dialogue with AI. Outside perspectives have not been systematically gathered; that limitation must travel with the account."]},
  {id:"aura-understanding",band:[.62,.74],label:"03 / Understanding / relationships between evidence",heading:"A connection is a question, too.",reveal:"line-unfold",paragraphs:["Patterns can link building, teaching and the wish to improve. They can also expose conflicts: freedom with commitment, leadership with over-ownership, curiosity with the depth an ambition needs.","Those connections are interpretations, not proof of psychological causation. A tidy explanation is not a reason to erase an unresolved tension."]},
  {id:"aura-model",band:[.74,.88],label:"04 / Model / the arrangement resolves",heading:"Useful because it can be wrong.",reveal:"tracking-settle",paragraphs:["The current model distinguishes facts, observations, patterns, interpretations, hypotheses, principles, unknowns and history. A claim should retain the status its evidence can support.","An earlier account of perfectionism became iterative excellence. An inflated account of coding became a named capability gap. Revision is part of the result, not an embarrassment to hide."]},
  {id:"aura-b08",band:[.88,1],label:"05 / Expression / the paths meet",heading:"Now the portfolio has something to represent.",reveal:"quiet-emergence",paragraphs:["The garden is one public expression of that process. The systems, questions, choices and contradictions belong to the same person, still becoming.","The task was never only to make a better-looking portfolio. It was to make the representation answerable to a better understanding of the person."],exits:[{href:"/stay/contact/",label:"Contact",place:"A quiet place to end"},{href:"/stay/work/",label:"Return to the evidence",place:"The Work"}]},
];
