/** Line breaks are an editorial score over the existing copy, not new content. */
export const titlePhrases: Record<string, readonly string[]> = {
  "Stay Awhile": ["Stay Awhile"],
  "A place, rather than a page.": ["A place,", "rather than a page."],
  "Scroll to enter the garden": ["Scroll to enter", "the garden"],
  "The Person": ["The Person"],
  "The person underneath the roles.": ["The person", "underneath the roles."],
  "What would make the ambition worth it?": ["What would make", "the ambition worth it?"],
  "Room to choose. Something to choose for.": ["Room to choose.", "Something to choose for."],
  "A calendar was only the surface.": ["A calendar", "was only the surface."],
  "Priority is not permission to take over.": ["Priority is not permission", "to take over."],
  "The failure is evidence. The response decides its value.": ["The failure is evidence.", "The response decides its value."],
  "Safety has a price of its own.": ["Safety has a price", "of its own."],
  "The garden was an expression all along.": ["The garden was", "an expression all along."],
  "The Builder": ["The Builder"],
  "The Thinker": ["The Thinker"],
  "The Leader": ["The Leader"],
  "The Future": ["The Future"],
  "Project AURA": ["Project AURA"],
  "I am ambitious, and I would rather say so plainly.": ["I am ambitious,", "and I would rather", "say so plainly."],
  "What would it take to become someone I could genuinely admire?": ["What would it take", "to become someone", "I could genuinely admire?"],
  "I have built real things. I am not yet the engineer I intend to become.": ["I have built real things.", "I am not yet the engineer", "I intend to become."],
  "We are animals that want things badly enough to invent them.": ["We are animals", "that want things badly", "enough to invent them."],
  "Failing is not the lesson. The return is.": ["Failing is not the lesson.", "The return is."],
  "I could build a life nothing could reach. I don’t want it.": ["I could build a life", "nothing could reach.", "I don’t want it."],
  "Ship it imperfect. Keep the debt on the books.": ["Ship it imperfect.", "Keep the debt on the books."],
  "I built a weekly MUN club for younger students, and then I ran it.": ["I built a weekly MUN club", "for younger students,", "and then I ran it."],
  "Ownership can become too much ownership.": ["Ownership can become", "too much ownership."],
  "The things I actually built.": ["The things", "I actually built."],
  "IGCSE Past Paper Logger & Analytics": ["IGCSE Past Paper", "Logger & Analytics"],
  "I am not interested in staying where I am.": ["I am not interested", "in staying where I am."],
  "A direction, not an arrival.": ["A direction,", "not an arrival."],
  "It started as a portfolio.": ["It started", "as a portfolio."],
  "If you made it this far, let’s talk.": ["If you made it this far,", "let’s talk."],
};

export type TypographyTempo = { reveal: number; gap: number; settle: number; hold: number; exit: number };
export const typographyTempos: Record<string, TypographyTempo> = {
  garden: { reveal: 1250, gap: 170, settle: 550, hold: 2800, exit: 780 },
  person: { reveal: 1400, gap: 190, settle: 600, hold: 3400, exit: 850 },
  builder: { reveal: 950, gap: 130, settle: 350, hold: 2700, exit: 650 },
  thinker: { reveal: 1700, gap: 240, settle: 800, hold: 4300, exit: 1100 },
  leader: { reveal: 1100, gap: 150, settle: 450, hold: 3000, exit: 750 },
  stories: { reveal: 1450, gap: 210, settle: 650, hold: 3400, exit: 950 },
  work: { reveal: 1000, gap: 140, settle: 350, hold: 3100, exit: 700 },
  future: { reveal: 1600, gap: 230, settle: 700, hold: 3700, exit: 1000 },
  aura: { reveal: 1750, gap: 220, settle: 700, hold: 4000, exit: 1100 },
  contact: { reveal: 1800, gap: 100, settle: 500, hold: 4000, exit: 1200 },
};
