"""Art-direction pass for the first four Stay Awhile Blender masters only.

Run with Blender 5.2 in background. Existing IDs, roots, animation pivots,
guide empties, collections and scene instances are retained. Geometry added
by this pass is deterministic and can be regenerated by rerunning the script.
"""
import bpy
import bmesh
import json
import math
import random
import struct
import sys
import zlib
from collections import defaultdict
from pathlib import Path
from mathutils import Vector
from mathutils.bvhtree import BVHTree

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from geometry import B, G, linear

ROUTES = {"garden": "00-garden.blend", "person": "01-person.blend", "builder": "02-builder.blend", "thinker": "03-thinker.blend"}
PALETTE = {
    "MOSS": "526B4D", "LEAF": "6C8A5F", "BARK": "796350", "STONE": "828379",
    "SAKURA": "E9AFBE", "WATER": "416F78", "DISTANT": "718568", "CLAY": "87715D",
    "PAPER": "E4DCC7", "LIGHT": "E8C796", "METAL": "454947", "ACCENT": "A78B56",
}

def color(h):
    return tuple(linear(int(h[i:i+2], 16) / 255) for i in (0, 2, 4)) + (1,)

def mat_for(key, lod):
    name="SA_M_" + key + ("_MOBILE" if lod == "mobile" and key in ("BARK", "PAPER") else "")
    m=bpy.data.materials.get(name) or bpy.data.materials.get("SA_M_"+key)
    if m is None:
        m=bpy.data.materials.new(name);m.use_nodes=True
        m.diffuse_color=color(PALETTE[key])
        m.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value=color(PALETTE[key])
    return m

def beauty_atlas(lod):
    """Packed route-local wood grain; the pre-existing shared atlas stays intact."""
    size=512 if lod=='mobile' else 1024
    path=HERE/f'beauty-timber.{lod}.png'
    if not path.exists() or path.stat().st_size>25000:
        raw=bytearray()
        for y in range(size):
            raw.append(0)
            if y<size//2:
                phase=int(2*math.sin(y/70))
                for x in range(size):
                    u=x*1024/size+phase
                    grain=7*math.sin(u/5.7)+4*math.sin(u/17.8)+2*math.sin(u/1.9)
                    shade=int(grain)
                    raw.extend((max(0,min(255,118+shade)),max(0,min(255,88+shade)),max(0,min(255,65+shade))))
            else:
                shade=int(math.sin(y/37))
                raw.extend(bytes((237+shade,232+shade,217+shade))*size)
        def chunk(kind,payload):
            return struct.pack('>I',len(payload))+kind+payload+struct.pack('>I',zlib.crc32(kind+payload)&0xffffffff)
        png=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',size,size,8,2,0,0,0))
        png+=chunk(b'IDAT',zlib.compress(bytes(raw),9))+chunk(b'IEND',b'')
        path.write_bytes(png)
    image=bpy.data.images.get('SA_BEAUTY_TIMBER_'+lod.upper())
    if not image:
        image=bpy.data.images.load(str(path),check_existing=False)
        image.name='SA_BEAUTY_TIMBER_'+lod.upper()
        image.pack()
    return image

def setup_materials():
    for key, h in PALETTE.items():
        for suffix in ("", "_MOBILE"):
            m = bpy.data.materials.get("SA_M_" + key + suffix)
            if not m or m.library: continue
            m.diffuse_color = color(h)
            p = m.node_tree.nodes.get("Principled BSDF")
            if not p: continue
            if key not in ("BARK", "PAPER"):
                p.inputs["Base Color"].default_value = color(h)
                for mix in m.node_tree.nodes:
                    if mix.type=='MIX_RGB' and mix.blend_type=='MULTIPLY' and not mix.inputs[1].is_linked:
                        mix.inputs[1].default_value=color(h)
            if key=='BARK':
                image=beauty_atlas('mobile' if suffix else 'desktop')
                for node in m.node_tree.nodes:
                    if node.type=='TEX_IMAGE':node.image=image
            p.inputs["Roughness"].default_value = {"WATER": .19, "STONE": .91, "BARK": .76, "PAPER": .92, "LEAF": .83}.get(key, .86)
            if key=="WATER":p.inputs["Metallic"].default_value=.08
            nodes = m.node_tree.nodes
            if not any(n.type == 'VERTEX_COLOR' for n in nodes):
                v = nodes.new("ShaderNodeVertexColor"); v.name = "SA_VERTEX_TONE"; v.layer_name = "COLOR_0"
                mul = nodes.new("ShaderNodeMixRGB"); mul.name = "SA_TONE_MULTIPLY"; mul.blend_type = 'MULTIPLY'; mul.inputs[0].default_value = 1
                upstream = p.inputs["Base Color"].links[0].from_socket if p.inputs["Base Color"].is_linked else None
                if upstream: m.node_tree.links.new(upstream, mul.inputs[1])
                else: mul.inputs[1].default_value = p.inputs["Base Color"].default_value
                m.node_tree.links.new(v.outputs["Color"], mul.inputs[2]); m.node_tree.links.new(mul.outputs[0], p.inputs["Base Color"])

def tune_light(route):
    scene = bpy.context.scene
    scene.world.node_tree.nodes["Background"].inputs[0].default_value = (.66, .73, .69, 1)
    scene.world.node_tree.nodes["Background"].inputs[1].default_value = .72
    sun = next((o for o in bpy.data.objects if o.type == 'LIGHT' and o.data.type == 'SUN' and not o.library), None)
    if sun:
        sun.data.energy = 2.0 if route != 'thinker' else 1.75
        sun.data.angle = .58 if route=='thinker' else .37
        sun.data.color = (1.0, .88, .75)
        sun.rotation_euler = Vector((-.5, -.72, -.62)).to_track_quat('-Z','Y').to_euler()
    scene.view_settings.view_transform = 'AgX'
    scene.view_settings.look = 'AgX - Medium High Contrast'
    scene.view_settings.exposure = .32
    scene.render.engine = 'CYCLES'; scene.cycles.samples = 36
    if route=='builder':
        fill=bpy.data.objects.get('SA_BUILDER_FILL_00')
        if not fill:
            data=bpy.data.lights.new('SA_BUILDER_FILL','AREA')
            fill=bpy.data.objects.new('SA_BUILDER_FILL_00',data)
            bpy.data.collections['07_LIGHT_GUIDES'].objects.link(fill)
        fill.location=B((0,2.75,-3.5))
        fill.rotation_euler=Vector((0,-1,0)).to_track_quat('-Z','Y').to_euler()
        fill.data.energy=330
        fill.data.shape='DISK';fill.data.size=6.0
        fill.data.color=(1.0,.89,.73)
    if route=='thinker':
        fill=bpy.data.objects.get('SA_THINKER_FILL_00')
        if not fill:
            data=bpy.data.lights.new('SA_THINKER_FILL','AREA')
            fill=bpy.data.objects.new('SA_THINKER_FILL_00',data)
            bpy.data.collections['07_LIGHT_GUIDES'].objects.link(fill)
        fill.location=B((-1.4,3.5,-2.5))
        fill.rotation_euler=(Vector(B((-3.5,.2,-5)))-fill.location).to_track_quat('-Z','Y').to_euler()
        fill.data.energy=380
        fill.data.shape='DISK';fill.data.size=7.5
        fill.data.color=(.88,.94,1.0)

class Sculpt:
    def __init__(self, aid, lod):
        self.aid, self.lod = aid, lod
        self.low = lod == 'mobile'
        self.col = bpy.data.collections[f"SA_{aid}_{lod.upper()}"]
        self.root = bpy.data.objects[f"SA_{aid}_{'MOBILE' if self.low else ''}ROOT_00"]
        self.groups = defaultdict(lambda: [[], [], []])
        self.seq = 60
    def add(self, verts, faces, key, parent=None, tones=None, smooth=False):
        parent = parent or self.root
        group = self.groups[(parent.name, key, smooth)]
        off = len(group[0]); group[0].extend([B(v) for v in verts]); group[1].extend([tuple(off+i for i in f) for f in faces])
        group[2].extend(tones if tones else [(1,1,1,1)]*len(verts))
    def tube(self, pts, radii, key='BARK', parent=None, sides=None, seed=0):
        sides = sides or (5 if self.low else 7); verts=[]; tones=[]; rng=random.Random(seed)
        for j,p in enumerate(pts):
            tangent=(Vector(pts[min(j+1,len(pts)-1)])-Vector(pts[max(0,j-1)])).normalized()
            ref=Vector((0,1,0)) if abs(tangent.y)<.93 else Vector((1,0,0))
            u=tangent.cross(ref).normalized();v=tangent.cross(u).normalized()
            for i in range(sides):
                a=2*math.pi*i/sides; jitter=1+rng.uniform(-.09,.09)
                verts.append(Vector(p)+radii[j]*jitter*(math.cos(a)*u+math.sin(a)*v))
                tone=.84+.16*rng.random();tones.append((tone,tone*.98,tone*.94,1))
        faces=[tuple(range(sides-1,-1,-1))]
        for j in range(len(pts)-1):
            for i in range(sides):faces.append((j*sides+i,j*sides+(i+1)%sides,(j+1)*sides+(i+1)%sides,(j+1)*sides+i))
        faces.append(tuple((len(pts)-1)*sides+i for i in range(sides)))
        self.add(verts,faces,key,parent,tones,True)
    def stone(self, c, scale, key='STONE', parent=None, seed=0, sides=None):
        rng=random.Random(seed); n=sides or (5 if self.low else 8); x,y,z=c; rx,ry,rz=scale
        rings=(0,.36,.8,1); verts=[]; tones=[]
        for j,h in enumerate(rings):
            for i in range(n):
                a=2*math.pi*i/n + .06*math.sin(seed+i*2)
                rad=(.72 if j==0 else 1 if j<3 else .67)*(1+rng.uniform(-.12,.12))
                verts.append((x+math.cos(a)*rx*rad, y+ry*h+(.025*rng.random() if j==3 else 0), z+math.sin(a)*rz*rad))
                t=.65+.25*rng.random(); moss=.08 if j==0 and rng.random()<.45 else 0
                tones.append((t-moss,t+.04,t-moss*.3,1))
        faces=[]
        for j in range(3):
            for i in range(n):faces.append((j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i))
        faces.append(tuple(3*n+i for i in range(n)))
        self.add(verts,faces,key,parent,tones)
    def leaf(self, start, end, width, key='LEAF', parent=None, tone=1, seed=0):
        s,e=Vector(start),Vector(end);d=e-s
        side=d.cross(Vector((0,1,.17)))
        if side.length<.01:side=Vector((1,0,0))
        side.normalize();mid=s+d*.55+Vector((0,width*.18,0));w=width
        verts=[s,mid-side*w*.55,mid+Vector((0,w*.2,0)),mid+side*w*.55,e]
        t=max(.45,min(1,tone));tones=[(t,t*(.95+.04*(seed%3)),t*.88,1)]*5
        self.add(verts,[(0,1,2),(0,2,3),(1,4,2),(2,4,3)],key,parent,tones,True)
    def box(self,c,d,key='BARK',parent=None,tone=.9):
        x,y,z=c;a,b,k=(v/2 for v in d)
        vs=[(x+sx*a,y+sy*b,z+sz*k) for sx,sy,sz in ((-1,-1,-1),(-1,-1,1),(1,-1,1),(1,-1,-1),(-1,1,-1),(-1,1,1),(1,1,1),(1,1,-1))]
        fs=[(0,1,2,3),(4,7,6,5),(0,4,5,1),(1,5,6,2),(2,6,7,3),(3,7,4,0)]
        self.add(vs,fs,key,parent,[(tone,tone*.95,tone*.87,1)]*8)
    def crown(self,c,r,key='DISTANT',parent=None,seed=0,sides=None):
        """Small ragged foliage volume: varied contour, hollow space between lobes."""
        rng=random.Random(seed); n=sides or (5 if self.low else 7)
        x,y,z=c;rx,ry,rz=r;vs=[];tones=[]
        for j,(h,spread) in enumerate(((-.73,.49),(-.18,1),(.43,.82),(.87,.37))):
            for i in range(n):
                ang=2*math.pi*i/n+seed*.31
                wobble=1+rng.uniform(-.19,.19)
                vs.append((x+math.cos(ang)*rx*spread*wobble,y+ry*(h+rng.uniform(-.07,.07)),z+math.sin(ang)*rz*spread*wobble))
                t=.72+.28*rng.random(); tones.append((t*(.88+.07*j),t,t*.78,1))
        fs=[tuple(range(n-1,-1,-1))]
        for j in range(3):
            for i in range(n):fs.append((j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i))
        fs.append(tuple(3*n+i for i in range(n)))
        self.add(vs,fs,key,parent,tones)
    def flush(self):
        for (pname,key,smooth),(vs,fs,tones) in self.groups.items():
            mesh=bpy.data.meshes.new(f"SA_{self.aid}_SCULPT_{self.seq:02}");mesh.from_pydata(vs,[],fs);mesh.update()
            bm=bmesh.new();bm.from_mesh(mesh);bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bm.to_mesh(mesh);bm.free()
            for poly in mesh.polygons:poly.use_smooth=smooth
            attr=mesh.color_attributes.new(name='COLOR_0',type='FLOAT_COLOR',domain='POINT')
            for i,t in enumerate(tones):attr.data[i].color=t
            if key in ('BARK','PAPER'):
                uv=mesh.uv_layers.new(name='UVMap')
                for poly in mesh.polygons:
                    for li in poly.loop_indices:
                        co=mesh.vertices[mesh.loops[li].vertex_index].co
                        uv.data[li].uv=(.05+(co.x*.11%1)*.88, (.54 if key=='BARK' else .04)+(co.z*.12%1)*.4)
            obj=bpy.data.objects.new(f"SA_{self.aid}_{'MOBILE' if self.low else ''}MESH_{self.seq:02}",mesh)
            self.seq+=1;self.col.objects.link(obj);obj.parent=bpy.data.objects[pname]
            main_lib=bpy.data.collections.get(f"LIB_{self.aid}_{self.lod}")
            if main_lib:main_lib.objects.link(obj)
            for lib in bpy.data.collections:
                if not lib.name.startswith(f"LIB_{self.aid}_{self.lod}_"):continue
                parent=obj.parent
                while parent:
                    if parent.name in lib.objects:
                        lib.objects.link(obj);break
                    parent=parent.parent
            mesh.materials.append(mat_for(key,self.lod));obj['beautyPass']=3

def clear_meshes(aid,lod):
    col=bpy.data.collections[f"SA_{aid}_{lod.upper()}"]
    for o in list(col.objects):
        if o.type=='MESH' and not o.library:
            bpy.data.objects.remove(o,do_unlink=True)

def original_parent(aid,lod,role,index=0):
    prefix='MOBILE' if lod=='mobile' else ''
    return bpy.data.objects.get(f"SA_{aid}_{prefix}{role}_{index:02}")

def shaped_path(a):
    variants=('STRAIGHT','BEND','JUNCTION')
    for vi,role in enumerate(variants):
        parent=original_parent('G02',a.lod,role)
        for i in range(6):
            t=(i+.5)/6
            if vi==0:x,z=0,2-t*4
            elif vi==1:x,z=4*(1-math.cos(t*math.pi/6)),2-8*math.sin(t*math.pi/6)
            else:
                ang=(-math.pi/2,math.pi/6,5*math.pi/6)[i//2];r=.6+(i%2)*1.15;x,z=math.cos(ang)*r,math.sin(ang)*r
            rng=random.Random(vi*41+i*13)
            x+=rng.uniform(-.19,.19);z+=rng.uniform(-.055,.055)
            a.stone((x,-.115+rng.uniform(-.009,.009),z),(.72+rng.uniform(-.10,.08),.085,.285+rng.uniform(-.025,.035)),parent=parent,seed=vi*31+i,
                    sides=5 if a.low else 7)
            if not a.low and i%2==0:
                a.stone((x+(.85 if i%4 else -.87),-.12,z+.1),(.17,.035,.15),parent=parent,seed=80+i,sides=5)
        # Fine moss at one edge; kept below the pedestrian crown.
        for i in range(4 if not a.low else 0):
            z=1.55-i*.95; x=(.76 if i%3 else -.83)+ .11*math.sin(i*3+vi)
            a.leaf((x,-.055,z),(x+.14,.075,z-.09),.12,'LEAF',parent,.85,i)

def sakura(a):
    rng=random.Random(710)
    trunk=[(0,0,0),(-.12,1.5,.06),(.06,2.9,-.17),(.3,4.08,-.24),(.22,5.05,-.28)]
    a.tube(trunk,[.35,.27,.19,.11,.045],seed=2)
    for i,(ang,reach,lift) in enumerate(((.25,2.9,1.55),(2.55,2.65,1.8),(4.55,3.05,1.4))):
        pivot=original_parent('G03',a.lod,'SWAY_'+chr(65+i))
        if pivot is None:continue
        d=Vector((math.cos(ang),0,math.sin(ang)))
        tip=Vector((d.x*reach,lift+1.4,d.z*reach))
        a.tube([(0,0,0),(d.x*.8,.75,d.z*.8),(d.x*reach*.7,lift,d.z*reach*.7),tip],
               [.18,.13,.075,.018],parent=pivot,seed=i+3)
        count=7 if a.low else 13
        for j in range(count):
            q=(j+.4)/(count+.7)
            side=(-1 if j%2 else 1)
            start=Vector((d.x*reach*(.2+.64*q),.4+(lift+.65)*q,d.z*reach*(.2+.64*q)))
            perp=Vector((-d.z,0,d.x));end=start+d*(.3+.45*(1-q))+perp*side*(.4+.65*(1-q))+Vector((0,.28+.32*rng.random(),0))
            a.tube([start,start.lerp(end,.54),end],[.055,.032,.008],parent=pivot,seed=20+i*20+j)
            # Distinct branch-led blossom sprays, with air between clusters.
            petals=5 if a.low else 9
            for k in range(petals):
                theta=k*2.4+.36*j;rad=(.11+.17*rng.random())*(.7+q*.3)
                c=end+Vector((math.cos(theta)*rad,rng.uniform(-.08,.11),math.sin(theta)*rad))
                a.leaf(c,c+Vector((math.cos(theta)*.13,.035,math.sin(theta)*.12)),.105 if not a.low else .14,'SAKURA',pivot,.75+.23*rng.random(),k)
        # Airy blossom masses follow the branch ends, leaving holes through
        # the crown rather than a single spherical cap.
        for j in range(4 if a.low else 7):
            q=.43+j*(.40/(3 if a.low else 6))
            perp=Vector((-d.z,0,d.x))
            c=d*(reach*q)+perp*((-1 if j%2 else 1)*(.43+.14*(j%3)))+Vector((0,1.25+lift*q+.13*(j%3),0))
            a.crown(c,(.39+.07*(j%2),.29+.055*(j%3),.35+.05*(j%2)),'SAKURA',pivot,seed=930+i*17+j)
    # Old bark texture alone reads flat in silhouette: exposed lateral scars.
    if not a.low:
        for j in range(8):
            y=.5+j*.46;a.tube([(.21,y,-.01),(.24,y+.14,-.04)],[.017,.01],parent=a.root,seed=180+j)

def shrub(a):
    for v in range(2):
        p=original_parent('G04',a.lod,'BUSH',v)
        rng=random.Random(40+v)
        a.tube([(0,0,0),(.04,.5,0)],[.06,.025],'BARK',p,5,seed=v)
        sprays=3 if a.low else 10
        for j in range(sprays):
            ang=j*2.399+v*.66;r=.22+.36*rng.random();h=.4+.23*rng.random()
            tip=(math.cos(ang)*r,h,math.sin(ang)*r*.75)
            a.tube([(0,.3,0),tip],[.019,.005],'BARK',p,4,seed=j)
            for k in range(1 if a.low else 3):
                aa=ang+k*1.8
                end=(tip[0]+math.cos(aa)*(.14+.05*k),tip[1]+.03*(k%2),tip[2]+math.sin(aa)*.15)
                a.leaf(tip,end,.12,'LEAF',p,.65+.34*rng.random(),k)
        for j in range(2 if a.low else 5):
            ang=j*2.42+v*.61
            a.crown((math.cos(ang)*.33,.45+.08*(j%2),math.sin(ang)*.3),(.36+.07*(j%2),.24,.31+.04*(j%3)),
                    'LEAF',p,seed=510+v*19+j,sides=4 if a.low else 5)

def grass(a):
    for v in range(3):
        p=original_parent('G05',a.lod,'TUFT',v)
        for j in range(6 if a.low else 20):
            ang=j*2.399+v*.7;r=.035+.09*(j%4)/3
            s=(math.cos(ang)*r,0,math.sin(ang)*r)
            e=(math.cos(ang)*(.16+.07*(j%3)),.17+.18*(j%5)/5,math.sin(ang)*(.16+.07*(j%3)))
            a.leaf(s,e,.025 if a.low else .03,'LEAF',p,.58+.4*((j*7)%13)/13,j)

def stone_kit(a):
    for v in range(4):
        p=original_parent('G06',a.lod,'STONE',v)
        a.stone((0,-.025,0),(.32+v*.16,.23+v*.06,.26+v*.15),parent=p,seed=v+30)

def water(a):
    n=3 if a.low else 9;vs=[];fs=[];tones=[]
    for j in range(n+1):
        for i in range(n+1):
            x=(i/n-.5)*12;z=(j/n-.5)*10
            y=.006*math.sin(i*1.7+j*.7)+.004*math.cos(i*.5-j*1.4)
            vs.append((x,y,z));shore=min(1,abs(x)/6,abs(z)/5)
            t=.78+.11*math.sin(i*.6+j*.4)+.08*shore;tones.append((t*.8,t*.96,t,1))
    for j in range(n):
        for i in range(n):
            k=j*(n+1)+i;fs.extend(((k,k+1,k+n+2),(k,k+n+2,k+n+1)))
    a.add(vs,fs,'WATER',tones=tones,smooth=True)

def distant_bank(a):
    rng=random.Random(201)
    count=5 if a.low else 7
    for i in range(count):
        x=-9+i*(18/(count-1))+rng.uniform(-.42,.42)
        h=4.1+(i%3)*.67+rng.uniform(-.28,.32)
        lean=rng.uniform(-.4,.4)
        a.tube([(x,0,0),(x+lean*.25,h*.48,.05),(x+lean,h*.78,-.15)],
               [.19,.14,.045],'BARK',seed=i)
        if not a.low:
            for side in (-1,1):
                a.tube([(x+lean*.2,h*.4,0),(x+side*.78+lean*.4,h*.63,0)],
                       [.075,.012],'BARK',seed=30+i*3+side)
        lobes=2 if a.low else 5
        for j in range(lobes):
            theta=i*.82+j*2.399
            off=(.63+.22*j) if a.low else (.48+.23*(j%4))
            cx=x+lean*.65+math.cos(theta)*off
            cy=h*((.62,.83)[j] if a.low else (.51,.68,.82,.73,.58)[j])
            cz=math.sin(theta)*off*.55
            a.crown((cx,cy,cz),(.65+.12*(i%2),.56+.10*(j%2),.56+.08*(j%3)),
                    'DISTANT',seed=610+i*13+j,sides=4 if a.low else 6)

TERRAIN_BVH={}
def terrain_height(x,z,low=False):
    # The actual G01 mesh contains a later camera-rail flattening pass. Ray
    # against that delivered surface instead of reconstructing the older
    # procedural height equation; the equation leaves planting in mid-air.
    col=bpy.data.collections['SA_G01_MOBILE' if low else 'SA_G01_DESKTOP']
    ground=next(o for o in col.objects if o.type=='MESH' and not o.get('beautyPass'))
    if ground.name not in TERRAIN_BVH:
        TERRAIN_BVH[ground.name]=BVHTree.FromPolygons(
            [v.co[:] for v in ground.data.vertices],
            [tuple(p.vertices) for p in ground.data.polygons])
    p,_,_,_=TERRAIN_BVH[ground.name].ray_cast(Vector((x,-z,10)),Vector((0,0,-1)))
    if p is None:raise RuntimeError(f'No G01 terrain below {x},{z}')
    return p.z

def repair_tea_deck_overlap(col):
    """Undo a broad legacy rail edit that skewed one deck plank over its neighbors."""
    from collections import deque
    obj=next(o for o in col.objects if o.type=='MESH' and not o.get('beautyPass'))
    if obj.get('beautyDeckOverlapRepair'):return
    mesh=obj.data
    candidate=[]
    for poly in mesh.polygons:
        pts=[G(mesh.vertices[i].co) for i in poly.vertices]
        if (all(abs(v[1]-.3)<.006 for v in pts) and
            min(v[0] for v in pts)<1.1 and max(v[0] for v in pts)>1.9 and
            max(v[2] for v in pts)-min(v[2] for v in pts)>3.5):candidate.append(poly)
    if len(candidate)!=1:raise RuntimeError(f'Expected one skewed T01 plank, found {len(candidate)} in {obj.name}')
    adjacency=defaultdict(set)
    for edge in mesh.edges:
        u,v=edge.vertices;adjacency[u].add(v);adjacency[v].add(u)
    group=set(candidate[0].vertices);todo=deque(group)
    while todo:
        for neighbor in adjacency[todo.popleft()]:
            if neighbor not in group:group.add(neighbor);todo.append(neighbor)
    count=0
    for index in group:
        vertex=mesh.vertices[index];x,y,z=G(vertex.co)
        if z< -1.9 and y<=.31 and .95<x<1.35:
            vertex.co=B(((x+.35)/.8,y,z));count+=1
    if count<2:raise RuntimeError(f'No distorted deck corners repaired in {obj.name}')
    mesh.update();obj['beautyDeckOverlapRepair']=True

def route_environment(a,route):
    # Owned ground and architecture receive edge planting without new IDs.
    if a.aid=='G01':
        # Garden-only camera basin in the shared terrain's local coordinates.
        # The world placement of G01 puts local Z 64..80 around Garden's rail.
        rng=random.Random(971)
        for i in range(18 if a.low else 38):
            x=rng.uniform(-10,10);z=rng.uniform(64,81)
            if abs(x)<1.65 or (x<0 and z<69):continue
            y=terrain_height(x,z,a.low)+.018
            if i%8==0:
                a.stone((x,y-.07,z),(.29+.12*rng.random(),.09,.24),seed=760+i,sides=6 if a.low else 8)
            else:
                a.crown((x,y+.12,z),(.32+.22*rng.random(),.13,.25+.14*rng.random()),
                        'MOSS',seed=820+i,sides=4 if a.low else 5)
        # A small mixed grove bridges the near path to the distant bank.
        # Individual crowns have different heights, leans, and open profiles.
        grove=[(3.55,58,4.2,'SAKURA'),(-4.7,59.5,5.2,'LEAF'),
               (6.9,53,5.6,'LEAF'),(-6.8,50.5,4.9,'SAKURA'),
               (4.5,43.5,6.2,'LEAF')]
        for i,(x,z,h,key) in enumerate(grove):
            y=terrain_height(x,z,a.low)
            lean=(-.25,.28,-.35,.38,.12)[i]
            a.tube([(x,y-.22,z),(x+lean*.3,y+h*.43,z-.08),
                    (x+lean,y+h*.7,z-.24)],
                   [.29+.025*(i%2),.16,.045],'BARK',seed=1350+i)
            a.crown((x,y+.08,z),(.42,.18,.38),'MOSS',seed=1365+i,sides=4 if a.low else 5)
            for j in range(3 if a.low else 6):
                angle=j*2.4+i*.61
                reach=.65+.31*(j%4)
                cx=x+lean+math.cos(angle)*reach
                cz=z-.24+math.sin(angle)*reach*.67
                cy=y+h*(.65+.075*(j%3))
                if not a.low:
                    a.tube([(x+lean*.45,y+h*.5,z-.1),(cx,cy,cz)],
                           [.065,.008],'BARK',seed=1380+i*7+j,sides=5)
                a.crown((cx,cy,cz),(.46+.10*(j%2),.43+.09*(i%2),.44+.07*(j%3)),
                        key,seed=1400+i*11+j,sides=4 if a.low else 5)
        # Irregular groundcover islands creep to the path without filling
        # its quiet center. All positions are deterministic and camera-led.
        for i in range(30 if a.low else 66):
            z=64+(i%22)*.73+rng.uniform(-.35,.35)
            side=-1 if i%2 else 1
            x=side*(1.7+.18*(i%6)+rng.uniform(-.18,1.6))
            y=terrain_height(x,z,a.low)+.015
            for j in range(1 if a.low else 2):
                ang=i*2.399+j*1.6
                a.leaf((x,y,z),(x+math.cos(ang)*.20,y+.19+.05*(i%3),z+math.sin(ang)*.18),
                       .055,'LEAF',tone=.71+.08*(i%4),seed=i+j)
        for i in range(9 if a.low else 20):
            z=63.5+(i%10)*1.7+rng.uniform(-.35,.35)
            x=(-1 if i%2 else 1)*(2.15+.23*(i%4)+rng.uniform(-.2,.4))
            y=terrain_height(x,z,a.low)
            a.crown((x,y+.12,z),(.33+.07*(i%3),.22,.26+.06*(i%2)),
                    'MOSS' if i%3 else 'LEAF',seed=1710+i,sides=4 if a.low else 5)
        for i in range(12 if a.low else 30):
            side=-1 if i%2 else 1
            x=side*(3.2+.47*(i%6)+rng.uniform(-.3,.5))
            z=42+(i%15)*1.65+rng.uniform(-.55,.55)
            y=terrain_height(x,z,a.low)
            if i%7==0:
                a.stone((x,y-.06,z),(.25,.11,.19),seed=1820+i,sides=5 if a.low else 7)
            else:
                a.crown((x,y+.12,z),(.38+.13*(i%3),.21,.31+.07*(i%2)),
                        'MOSS' if i%4 else 'LEAF',seed=1840+i,sides=4 if a.low else 5)
    if a.aid=='P01':
        rng=random.Random(421)
        for i in range(36 if not a.low else 16):
            ang=2*math.pi*i/(36 if not a.low else 16);r=6.7+.5*rng.random()
            x,z=math.cos(ang)*r,math.sin(ang)*r*1.45
            if i%5==0:a.stone((x,-.045,z),(.3,.13,.23),seed=200+i)
            else:
                for k in range(2 if a.low else 3):
                    aa=ang+k*.9;a.leaf((x,0,z),(x+math.cos(aa)*.13,.18+.07*k,z+math.sin(aa)*.13),.04,'LEAF',tone=.68+.2*k,seed=i)
        for i in range(9 if a.low else 20):
            ang=i*2.399+(.2 if i%3 else -.18);r=5.8+.9*rng.random()
            x,z=math.cos(ang)*r,math.sin(ang)*r*1.43
            if (x>1.5 and -2<z<2) or (x< -2 and z< -7):continue
            a.crown((x,.22,z),(.35+.12*rng.random(),.23,.30+.12*rng.random()),
                    'MOSS' if i%4 else 'LEAF',seed=920+i,sides=4 if a.low else 5)
    if a.aid=='P03':
        # Two interlocking, tapered roots make a walkable arch rather than
        # the former pair of diagonal logs.
        for side in (-1,1):
            a.tube([(side*1.75,0,1.05),(side*1.64,.62,.75),(side*1.43,1.18,.38),
                    (side*.95,1.83,-.13),(side*.34,2.17,-.46)],
                   [.28,.24,.17,.105,.026],'BARK',seed=310+side)
            for j in range(3 if a.low else 5):
                base=(side*(1.56-.21*j),.55+j*.27,.54-j*.18)
                tip=(base[0]+side*(.36+.06*(j%2)),base[1]+.23,base[2]-.28)
                a.tube([base,tip],[.063,.012],'BARK',seed=340+j+side)
                a.leaf(tip,(tip[0]+side*.15,tip[1]+.13,tip[2]-.07),.11,
                       'LEAF',tone=.82,seed=700+j)
            a.crown((side*1.46,.4,.88),(.45,.20,.42),'MOSS',seed=870+side,sides=4 if a.low else 5)
            for j in range(2 if a.low else 3):
                x=side*(1.38-.24*j);z=.29-.21*j
                a.crown((x,1.44+.25*j,z),(.31,.24,.28),
                        'SAKURA',seed=1510+j+side*10,sides=4 if a.low else 5)
        a.tube([(-.35,2.13,-.45),(0,2.27,-.48),(.35,2.13,-.45)],
               [.06,.075,.06],'BARK',seed=1540,sides=5 if a.low else 7)
    if a.aid=='B01':
        # A weathered foundation skirt and floor-board edges establish a built place.
        for i in range(8 if not a.low else 5):
            z=-.1-i*.78;a.box((0,.025,z),(5.6,.07,.63),'BARK',tone=.7+.025*(i%3))
        for x in (-2.75,2.75):a.box((x,.08,-2.7),(.12,.17,6.2),'BARK',tone=.61)
        for x in (-2.55,2.55):
            for z in (-.15,-2.45,-4.75):
                a.box((x,.19,z),(.22,.08,.23),'STONE',tone=.77)
    if a.aid=='T01':
        # Low shoreline framing around the tea deck; preserve a spacious open water face.
        rng=random.Random(603)
        for i in range(18 if not a.low else 9):
            theta=math.pi*.45+i*math.pi*1.35/(18 if not a.low else 9)
            x=2.9*math.cos(theta);z=-.7+2.8*math.sin(theta)
            a.stone((x,-.085,z),(.36+.18*rng.random(),.12,.28+.13*rng.random()),seed=300+i)
            if i%3==0:
                for k in range(3):a.leaf((x,0,z),(x+.12*math.cos(k*2),.2+.1*k,z+.12*math.sin(k*2)),.045,'LEAF',tone=.63+.1*k,seed=i)
    if a.aid=='P02':
        for i in range(5):a.box((-.98+i*.49,.58,0),(.44,.045,.84),'BARK',tone=.69+.04*(i%3))
        for x in (-1.18,1.18):a.box((x,.43,0),(.08,.27,.71),'BARK',tone=.58)
        for x in (-.78,.78):a.box((x,.70,-.36),(.075,.28,.075),'BARK',tone=.7)
        a.box((0,.82,-.38),(1.73,.07,.08),'BARK',tone=.73)
    if a.aid=='B02':
        for i in range(6):
            p=original_parent('B02',a.lod,'POST',i)
            if not p:continue
            for y in (.54,2.72):a.box((0,y,0),(.235,.05,.235),'BARK',p,.59)
            a.box((.14,2.82,0),(.055,.27,.17),'BARK',p,.56)
    if a.aid=='B03':
        for i in range(7):
            p=original_parent('B03',a.lod,'BEAM',i)
            if not p:continue
            a.box((0,-.13,0),(.11,.055,3.7 if i>=5 else 2.9),'BARK',p,.57)
    if a.aid=='B05':
        p=original_parent('B05',a.lod,'BENCH',0)
        if p:
            for i in range(5):a.box((-1.65+i*.83,.965,0),(.77,.035,1.0),'BARK',p,.75+.03*(i%3))
            a.box((0,.45,-.46),(3.9,.075,.08),'BARK',p,.58)
            # End-grain tenons and measured working marks stay on the table;
            # a tall rack had cut through the intended open camera view.
            for x in (-1.82,1.82):
                for z in (-.43,.40):a.box((x,.98,z),(.075,.075,.09),'STONE',p,.76)
            for j in range(4 if a.low else 7):
                x=-1.25+j*(2.5/(3 if a.low else 6))
                a.box((x,1.002,-.36),(.018,.007,.26),'STONE',p,.68+.025*(j%3))
            for x in (-1.48,1.48):
                a.box((x,1.032,.34),(.24,.085,.22),'BARK',p,.82)
                a.box((x,1.086,.34),(.09,.027,.22),'BARK',p,.67)
    if a.aid=='G14':
        rng=random.Random(1112)
        for i in range(3 if a.low else 5):
            ang=i*2.399;rad=.66+.17*rng.random()
            x,z=math.cos(ang)*rad,math.sin(ang)*rad*.77
            a.crown((x,.10,z),(.18+.05*rng.random(),.12,.15+.05*rng.random()),
                    'MOSS',seed=1112+i,sides=4 if a.low else 5)
            if i%3==0:a.stone((x*1.3,-.04,z*1.4),(.14,.055,.11),seed=1180+i)
    if a.aid=='T01':
        # Narrow weathered board seams, exposed end grain and a planted shore.
        for i in range(0 if a.low else 6):
            x=-1.7+i*(3.4/5)
            a.box((x,.309,0),(.025,.009,3.83),'BARK',tone=.58+.07*(i%3))
        if not a.low:a.box((0,.21,-1.9),(3.95,.13,.085),'BARK',tone=.65)
        for i in range(1 if a.low else 4):
            ang=-.3+i*math.pi*1.25/(1 if a.low else 4)
            x=2.1+math.cos(ang)*.45;z=math.sin(ang)*2.15
            if i%2==0:a.stone((x,-.065,z),(.25,.11,.22),seed=1220+i,sides=5 if a.low else 8)
            else:a.crown((x,.13,z),(.25,.16,.21),'MOSS',seed=1260+i,sides=4 if a.low else 5)
    if a.aid=='T02':
        for i in range(7):
            p=original_parent('T02',a.lod,'FREEDOM',i)
            if p:
                a.stone((.02*(i%3-1),-.09,0),(.46+.1*(i%3),.14+.025*(i%2),.40+.055*((i+1)%3)),parent=p,seed=400+i)
                if i%2==0:a.stone((.38,-.11,-.24),(.13,.07,.12),parent=p,seed=450+i,sides=5 if a.low else 7)

def scene_route(route):
    source=HERE/ROUTES[route]
    bpy.ops.wm.open_mainfile(filepath=str(source),load_ui=False)
    setup_materials();tune_light(route)
    owned={"garden":['G01','G02','G03','G04','G05','G06','G07','G11','G14'],"person":['P01','P02','P03'],"builder":['B01','B02','B03','B05'],"thinker":['T01','T02']}[route]
    for aid in owned:
        for lod in ('desktop','mobile'):
            a=Sculpt(aid,lod)
            for o in list(a.col.objects):
                if o.get('beautyPass',0)>=2:bpy.data.objects.remove(o,do_unlink=True)
            # Only entirely rebuilt kits have their original meshes removed.
            if aid in ('G02','G03','G04','G05','G06','G07','G11','P03','T02'):clear_meshes(aid,lod)
            if aid=='G02':shaped_path(a)
            elif aid=='G03':sakura(a)
            elif aid=='G04':shrub(a)
            elif aid=='G05':grass(a)
            elif aid=='G06':stone_kit(a)
            elif aid=='G07':water(a)
            elif aid=='G11':distant_bank(a)
            else:route_environment(a,route)
            a.flush()
            if aid=='G14':
                for o in a.col.objects:
                    if o.type!='MESH' or o.get('beautyPass') or o.get('beautyMarkerProportions'):continue
                    for vertex in o.data.vertices:
                        vertex.co.x*=.72
                        vertex.co.y*=.74
                        vertex.co.z*=1.05
                    o.data.update()
                    o['beautyMarkerProportions']=True
            if aid=='T01':repair_tea_deck_overlap(a.col)
    # The full garden floor uses sober greens with soft variation, retaining
    # the original topography/zone flattening and all route placements.
    if route=='garden':
        for lod in ('DESKTOP','MOBILE'):
            col=bpy.data.collections['SA_G01_'+lod]
            for o in col.objects:
                if o.type!='MESH':continue
                attr=o.data.color_attributes.get('COLOR_0')
                if not attr:continue
                for i,v in enumerate(o.data.vertices):
                    x,y,z=G(v.co)
                    t=.70+.16*math.sin(x*.17+z*.12)+.10*math.cos(x*.39-z*.28)
                    t=max(.48,min(.99,t))
                    if 62<z<82 and abs(x)<2.8:
                        attr.data[i].color=(min(1,t*1.18),t*.81,t*.62,1)
                    else:
                        attr.data[i].color=(t*(.86+.08*math.sin(z*.12)),t,t*.77,1)
    setup_materials()
    info=json.loads(bpy.data.texts['READ_ME'].as_string())
    note='2026-09-23 beauty pass: original sculpted planting, branching, stonework and first-four route details; no third-party model assets.'
    if note not in info['artistNotes']:info['artistNotes'].append(note)
    txt=bpy.data.texts['READ_ME'];txt.clear();txt.write(json.dumps(info,indent=2))
    bpy.context.scene['beautyPassVersion']=7
    bpy.context.preferences.filepaths.save_version=0
    bpy.ops.wm.save_as_mainfile(filepath=str(source),compress=True)
    print('BEAUTIFIED',route,flush=True)

if __name__=='__main__':
    only=sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else list(ROUTES)
    for route in only:scene_route(route)
